-- DCS-BIOS Hub Script: forward full cockpit state to SimTutor via UDP.
-- NOTE: This script is for the DCS-BIOS Hub (external app), not for DCS Export.

local SIMTUTOR_HOST = "127.0.0.1"
local SIMTUTOR_PORT = 7790

-- Option 1: point directly to a Lua file generated by catalog_loader.py
local CONTROL_LIST_PATH = nil
-- Option 2: point to a directory containing dcs_bios_controls_<aircraft>.lua
local CONTROL_LIST_DIR = nil

local SEND_DELTA_ONLY = false

local seq = 0
local last_aircraft = ""
local controls = {}
local last_values = {}
local udp = nil

local function json_escape(s)
    s = s:gsub("\\", "\\\\")
    s = s:gsub("\"", "\\\"")
    s = s:gsub("\n", "\\n")
    s = s:gsub("\r", "\\r")
    s = s:gsub("\t", "\\t")
    return s
end

local function json_encode_value(v)
    local t = type(v)
    if t == "string" then
        return "\"" .. json_escape(v) .. "\""
    elseif t == "number" or t == "boolean" then
        return tostring(v)
    elseif t == "table" then
        local is_array = true
        local n = 0
        for k, _ in pairs(v) do
            n = n + 1
            if type(k) ~= "number" then
                is_array = false
                break
            end
        end
        local items = {}
        if is_array then
            for i = 1, n do
                items[#items + 1] = json_encode_value(v[i])
            end
            return "[" .. table.concat(items, ",") .. "]"
        else
            for k, val in pairs(v) do
                items[#items + 1] = "\"" .. json_escape(tostring(k)) .. "\":" .. json_encode_value(val)
            end
            return "{" .. table.concat(items, ",") .. "}"
        end
    end
    return "null"
end

local function json_encode(tbl)
    return json_encode_value(tbl)
end

local function try_open_udp()
    if udp then
        return true
    end
    local ok, socket = pcall(require, "socket")
    if ok and socket and socket.udp then
        udp = socket.udp()
        udp:settimeout(0)
        return true
    end
    if hub and type(hub.sendUdp) == "function" then
        return true
    end
    return false
end

local function send_udp(payload)
    if not try_open_udp() then
        return
    end
    if udp then
        pcall(function()
            udp:sendto(payload, SIMTUTOR_HOST, SIMTUTOR_PORT)
        end)
        return
    end
    if hub and type(hub.sendUdp) == "function" then
        pcall(function()
            hub.sendUdp(SIMTUTOR_HOST, SIMTUTOR_PORT, payload)
        end)
    end
end

local function load_controls_for_aircraft(aircraft)
    local path = CONTROL_LIST_PATH
    if not path and CONTROL_LIST_DIR then
        path = CONTROL_LIST_DIR .. "/dcs_bios_controls_" .. aircraft .. ".lua"
    end
    if not path then
        return false
    end
    local ok, data = pcall(dofile, path)
    if not ok or type(data) ~= "table" then
        return false
    end
    if data.controls then
        controls = data.controls
    else
        controls = data
    end
    return true
end

local function get_wall_time()
    local seconds = os.time() or 0
    local frac = os.clock() or 0
    return seconds + (frac - math.floor(frac))
end

local function build_delta()
    local delta = {}
    for _, c in ipairs(controls) do
        local id = c.id
        local kind = c.kind
        local value = nil
        if kind == "string" then
            value = hub.getSimString(id)
        else
            value = hub.getSimInteger(id)
            if value == -1 then
                value = nil
            end
        end
        if value ~= nil and last_values[id] ~= value then
            last_values[id] = value
            delta[id] = value
        end
    end
    return delta
end

hub.registerOutputCallback(function()
    local acft = hub.getSimString("MetadataStart/_ACFT_NAME") or ""
    if acft == "" then
        return
    end
    if acft ~= last_aircraft then
        last_aircraft = acft
        last_values = {}
        load_controls_for_aircraft(acft)
    end
    if #controls == 0 then
        return
    end

    local delta = build_delta()
    if next(delta) == nil then
        return
    end
    if not SEND_DELTA_ONLY then
        delta = last_values
    end
    seq = seq + 1
    local payload = {
        seq = seq,
        t_wall = get_wall_time(),
        aircraft = acft,
        bios = delta
    }
    send_udp(json_encode(payload))
end)

